# Generated by Django 5.2.8 on 2025-11-07 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Grupo')),
                ('codigo_acesso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('is_representante', models.BooleanField(verbose_name='É líder/representante?')),
                ('status_confirmacao', models.CharField(max_length=50, verbose_name='Status de presença')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidados', to='core.grupo')),
            ],
        ),
    ]
