# Generated by Django 5.2.8 on 2025-12-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='status_confirmacao',
            field=models.BooleanField(default=False, verbose_name='Status de confirmação do grupo'),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='status_confirmacao',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('pendente', 'Pendente')], default='pendente', max_length=50, verbose_name='Status de presença'),
        ),
    ]
