# Generated by Django 5.2.8 on 2026-02-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grupo_status_confirmacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug do Grupo'),
            preserve_default=False,
        ),
    ]
