# Generated by Django 5.2.8 on 2026-02-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grupo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='slug',
        ),
    ]
