# Generated by Django 5.2.8 on 2026-02-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_grupo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Grupo'),
        ),
    ]
