# Generated by Django 5.2.8 on 2026-02-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_grupo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Grupo'),
        ),
    ]
