# Generated by Django 5.2.8 on 2026-02-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_grupo_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convidado',
            name='is_representante',
        ),
    ]
