# Generated by Django 5.2.8 on 2026-07-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_convidado_is_representante'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_convidado 
                ALTER COLUMN status_confirmacao 
                TYPE boolean 
                USING (CASE WHEN status_confirmacao = 'pendente' THEN FALSE ELSE TRUE END);
            """,
            reverse_sql="""
                ALTER TABLE core_convidado 
                ALTER COLUMN status_confirmacao 
                TYPE varchar(255) 
                USING (CASE WHEN status_confirmacao = FALSE THEN 'pendente' ELSE 'confirmado' END);
            """
        ),
        migrations.AlterField(
            model_name='convidado',
            name='status_confirmacao',
            field=models.BooleanField(default=False, verbose_name='Status de confirmação do Convidado'),
        ),
    ]
