# Generated by Django 5.2.8 on 2026-07-16 16:48
#
# Rewritten to avoid Postgres-only raw SQL (`ALTER COLUMN ... TYPE ... USING`),
# which is invalid syntax on SQLite. As originally written this migration made
# `manage.py test` (settings.py forces SQLite for tests) and any local/SQLite
# development setup fail immediately with "OperationalError: near ALTER: syntax
# error". Converts the CharField ('pendente'/other) to BooleanField via a
# temporary column + data migration, which works identically on every backend.
#
# NOTE: if this migration has already been applied against a real production
# database with the old raw-SQL version, replacing its contents here won't
# retroactively change what already ran there -- Django won't re-apply a
# migration it has already recorded as applied. This rewrite only matters for
# anyone running `migrate` against a fresh database (tests, local SQLite, or a
# not-yet-deployed production DB) from this point forward.

from django.db import migrations, models


def populate_status_confirmacao_bool(apps, schema_editor):
    Convidado = apps.get_model('core', 'Convidado')
    for convidado in Convidado.objects.all():
        Convidado.objects.filter(pk=convidado.pk).update(
            status_confirmacao_bool=(convidado.status_confirmacao != 'pendente')
        )


def populate_status_confirmacao_str(apps, schema_editor):
    Convidado = apps.get_model('core', 'Convidado')
    for convidado in Convidado.objects.all():
        Convidado.objects.filter(pk=convidado.pk).update(
            status_confirmacao='confirmado' if convidado.status_confirmacao_bool else 'pendente'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_convidado_is_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='status_confirmacao_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            populate_status_confirmacao_bool,
            reverse_code=populate_status_confirmacao_str,
        ),
        migrations.RemoveField(
            model_name='convidado',
            name='status_confirmacao',
        ),
        migrations.RenameField(
            model_name='convidado',
            old_name='status_confirmacao_bool',
            new_name='status_confirmacao',
        ),
        migrations.AlterField(
            model_name='convidado',
            name='status_confirmacao',
            field=models.BooleanField(default=False, verbose_name='Status de confirmação do Convidado'),
        ),
    ]
